---
title: "Perceived BMI and Oral Contraceptive Use"
author: "Holly Smith & Jenine K. Harris"
date: "August 4, 2021"
output:
  html_document:
    df_print: paged
---


```{r}
# install the libraries loaded before running this code chunk
library(tidyverse)
library(haven)
library(nnet)
library(lmtest)
library(nhanesA)
library(labelled)
library(plyr)
library(mlogit)
library(table1)

# importing the NHANES data and merging
# DEMO
# BMX
# HIQ
# WHQ
# RHQ
# HSQ
# Years E-J (2007-2018)
demo_e <- remove_labels(nhanes('DEMO_E'),user_na_to_na = FALSE, keep_var_label = FALSE)
bmx_e <- remove_labels(nhanes('BMX_E'),user_na_to_na = FALSE, keep_var_label = FALSE)
hiq_e <- remove_labels(nhanes('HIQ_E'),user_na_to_na = FALSE, keep_var_label = FALSE)
whq_e <- remove_labels(nhanes('WHQ_E'),user_na_to_na = FALSE, keep_var_label = FALSE)
rhq_e <- remove_labels(nhanes('RHQ_E'),user_na_to_na = FALSE, keep_var_label = FALSE)
hsq_e <- remove_labels(nhanes('HSQ_E'),user_na_to_na = FALSE, keep_var_label = FALSE)
demo_f <- remove_labels(nhanes('DEMO_F'),user_na_to_na = FALSE, keep_var_label = FALSE)
bmx_f <- remove_labels(nhanes('BMX_F'),user_na_to_na = FALSE, keep_var_label = FALSE)
hiq_f <- remove_labels(nhanes('HIQ_F'),user_na_to_na = FALSE, keep_var_label = FALSE)
whq_f <- remove_labels(nhanes('WHQ_F'),user_na_to_na = FALSE, keep_var_label = FALSE)
rhq_f <- remove_labels(nhanes('RHQ_F'),user_na_to_na = FALSE, keep_var_label = FALSE)
hsq_f <- remove_labels(nhanes('HSQ_F'),user_na_to_na = FALSE, keep_var_label = FALSE)
demo_g <- remove_labels(nhanes('DEMO_G'),user_na_to_na = FALSE, keep_var_label = FALSE)
bmx_g <- remove_labels(nhanes('BMX_G'),user_na_to_na = FALSE, keep_var_label = FALSE)
hiq_g <- remove_labels(nhanes('HIQ_G'),user_na_to_na = FALSE, keep_var_label = FALSE)
whq_g <- remove_labels(nhanes('WHQ_G'),user_na_to_na = FALSE, keep_var_label = FALSE)
rhq_g <- remove_labels(nhanes('RHQ_G'),user_na_to_na = FALSE, keep_var_label = FALSE)
hsq_g <- remove_labels(nhanes('HSQ_G'),user_na_to_na = FALSE, keep_var_label = FALSE)
demo_h <- remove_labels(nhanes('DEMO_H'),user_na_to_na = FALSE, keep_var_label = FALSE)
bmx_h <- remove_labels(nhanes('BMX_H'),user_na_to_na = FALSE, keep_var_label = FALSE)
hiq_h <- remove_labels(nhanes('HIQ_H'),user_na_to_na = FALSE, keep_var_label = FALSE)
whq_h <- remove_labels(nhanes('WHQ_H'),user_na_to_na = FALSE, keep_var_label = FALSE)
rhq_h <- remove_labels(nhanes('RHQ_H'),user_na_to_na = FALSE, keep_var_label = FALSE)
hsq_h <- remove_labels(nhanes('HSQ_H'),user_na_to_na = FALSE, keep_var_label = FALSE)
demo_i <- remove_labels(nhanes('DEMO_I'),user_na_to_na = FALSE, keep_var_label = FALSE)
bmx_i <- remove_labels(nhanes('BMX_I'),user_na_to_na = FALSE, keep_var_label = FALSE)
hiq_i <- remove_labels(nhanes('HIQ_I'),user_na_to_na = FALSE, keep_var_label = FALSE)
whq_i <- remove_labels(nhanes('WHQ_I'),user_na_to_na = FALSE, keep_var_label = FALSE)
rhq_i <- remove_labels(nhanes('RHQ_I'),user_na_to_na = FALSE, keep_var_label = FALSE)
hsq_i <- remove_labels(nhanes('HSQ_I'),user_na_to_na = FALSE, keep_var_label = FALSE)
demo_j <- remove_labels(nhanes('DEMO_J'),user_na_to_na = FALSE, keep_var_label = FALSE)
bmx_j <- remove_labels(nhanes('BMX_J'),user_na_to_na = FALSE, keep_var_label = FALSE)
hiq_j <- remove_labels(nhanes('HIQ_J'),user_na_to_na = FALSE, keep_var_label = FALSE)
whq_j <- remove_labels(nhanes('WHQ_J'),user_na_to_na = FALSE, keep_var_label = FALSE)
rhq_j <- remove_labels(nhanes('RHQ_J'),user_na_to_na = FALSE, keep_var_label = FALSE)
hsq_j <- remove_labels(nhanes('HSQ_J'),user_na_to_na = FALSE, keep_var_label = FALSE)

# merge for each year
e_nhanes <- Reduce(function(x, y) merge(x, y, by = "SEQN", all = TRUE), list(demo_e, bmx_e, hiq_e, whq_e, rhq_e, hsq_e))  
f_nhanes <- Reduce(function(x, y) merge(x, y, by = "SEQN", all = TRUE), list(demo_f, bmx_f, hiq_f, whq_f, rhq_f, hsq_f))  
g_nhanes <- Reduce(function(x, y) merge(x, y, by = "SEQN", all = TRUE), list(demo_g, bmx_g, hiq_g, whq_g, rhq_g, hsq_g)) 
h_nhanes <- Reduce(function(x, y) merge(x, y, by = "SEQN", all = TRUE), list(demo_h, bmx_h, hiq_h, whq_h, rhq_h, hsq_h))  
i_nhanes <- Reduce(function(x, y) merge(x, y, by = "SEQN", all = TRUE), list(demo_i, bmx_i, hiq_i, whq_i, rhq_i, hsq_i))  
j_nhanes <- Reduce(function(x, y) merge(x, y, by = "SEQN", all = TRUE), list(demo_j, bmx_j, hiq_j, whq_j, rhq_j, hsq_j)) 

# reduce files to needed variables
e_nhanes_small <- e_nhanes %>% 
  select(SEQN,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMDEDUC3,DMDEDUC2,HIQ011,
         INDFMPIR,HSD010,RHQ420,WHQ030,BMXBMI,BMXWT,BMXHT)
f_nhanes_small <- f_nhanes %>% 
  select(SEQN,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMDEDUC3,DMDEDUC2,HIQ011,
         INDFMPIR,HSD010,RHQ420,WHQ030,BMXBMI,BMXWT,BMXHT)
g_nhanes_small <- g_nhanes %>% 
  select(SEQN,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMDEDUC3,DMDEDUC2,HIQ011,
         INDFMPIR,HSD010,RHQ420,WHQ030,BMXBMI,BMXWT,BMXHT)
h_nhanes_small <- h_nhanes %>% 
  select(SEQN,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMDEDUC3,DMDEDUC2,HIQ011,
         INDFMPIR,HSD010,RHQ420,WHQ030,BMXBMI,BMXWT,BMXHT)
i_nhanes_small <- i_nhanes %>% 
  select(SEQN,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMDEDUC3,DMDEDUC2,HIQ011,
         INDFMPIR,HSD010,RHQ420,WHQ030,BMXBMI,BMXWT,BMXHT)
j_nhanes_small <- j_nhanes %>% 
  select(SEQN,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMDEDUC3,DMDEDUC2,HIQ011,
         INDFMPIR,HSD010,RHQ420,WHQ030,BMXBMI,BMXWT,BMXHT) 
capdat <- bind_rows(e_nhanes_small, f_nhanes_small, g_nhanes_small, h_nhanes_small,
                i_nhanes_small, j_nhanes_small)
# create a BMI variable to compare to the one contained in the data
capdat$bmiCalc <- capdat$BMXWT/(capdat$BMXHT/100)^2
```

# Data management (recoding and adding labels)

```{r}
# get the subsample for analysis

capdat$MEC[capdat$RIDSTATR == 1] <- "interview"
capdat$MEC[capdat$RIDSTATR == 2] <- "examined"

capdat$sex[capdat$RIAGENDR == 1] <- "male"
capdat$sex[capdat$RIAGENDR == 2] <- "female"

capdat$agesamp[capdat$RIDAGEYR >= 20 & capdat$RIDAGEYR <= 49] <- "subsample"
capdat$agesamp[capdat$RIDAGEYR < 20 & capdat$RIDAGEYR > 49] <- "notsub"

##### Covariates #####

capdat$eth[capdat$RIDRETH1 == 1] <- "Hispanic"
capdat$eth[capdat$RIDRETH1 == 2] <- "Hispanic"
capdat$eth[capdat$RIDRETH1 == 3] <- "White"
capdat$eth[capdat$RIDRETH1 == 4] <- "Black"
capdat$eth[capdat$RIDRETH1 == 5] <- "Other"

### education
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 0] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 1] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 2] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 3] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 4] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 5] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 6] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 7] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 8] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 9] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 10] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 11] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 12] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 55] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR <= 19 & 
             capdat$DMDEDUC3 == 66] <- "Did not finish HS"
capdat$cedu[capdat$RIDAGEYR >= 20 & 
                capdat$DMDEDUC3 == 13] <- "Finished HS"
capdat$cedu[capdat$RIDAGEYR >= 20 & 
                capdat$DMDEDUC3 == 14] <- "Finished HS"
capdat$cedu[capdat$RIDAGEYR >= 20 & 
                capdat$DMDEDUC3 == 15] <- "Finished HS"

capdat$education[capdat$RIDAGEYR >= 20 & 
                   capdat$DMDEDUC2 %in% c(1,2) | 
                   capdat$cedu == "Did not finish HS"] <- "Below High School"
capdat$education[capdat$cedu == "Finished HS" |
                   capdat$DMDEDUC2 == 3] <- "Finished HS"
capdat$education[capdat$DMDEDUC2 == 4] <- "Some College"
capdat$education[capdat$DMDEDUC2 == 5] <- "Bachelor and Above"

capdat$insur[capdat$HIQ011 == 1] <- "Not Insured"
capdat$insur[capdat$HIQ011 == 2] <- "Insured"

capdat$poverty[capdat$INDFMPIR >= 0.0 & capdat$INDFMPIR < 1.0] <- "Near Poor"
capdat$poverty[capdat$INDFMPIR >= 1.0 & capdat$INDFMPIR < 2.0] <- "Poor"
capdat$poverty[capdat$INDFMPIR >=2.0 & capdat$INDFMPIR < 4.0] <- "Middle Income"
capdat$poverty[capdat$INDFMPIR >= 4.0] <- "High Income"

capdat$health[capdat$HSD010 == 1] <- "Good/excellent"
capdat$health[capdat$HSD010 == 2] <- "Good/excellent"
capdat$health[capdat$HSD010 == 3] <- "Good/excellent"
capdat$health[capdat$HSD010 == 4] <- "Fair/poor"
capdat$health[capdat$HSD010 == 5] <- "Fair/poor"

capdat$ocp[capdat$RHQ420 == 1] <- "Use"
capdat$ocp[capdat$RHQ420 == 2] <- "Non-Use"

capdat$percbmi[capdat$WHQ030 == 1] <- "Overweight"
capdat$percbmi[capdat$WHQ030 == 2] <- "Underweight"
capdat$percbmi[capdat$WHQ030 == 3] <- "Normal Weight"

capdat$actbmi[capdat$BMXBMI >= 1 & capdat$BMXBMI < 18.5] <- "Underweight"
capdat$actbmi[capdat$BMXBMI >= 18.5 & capdat$BMXBMI < 25] <- "Normal Weight"
capdat$actbmi[capdat$BMXBMI >= 25 & capdat$BMXBMI < 30] <- "Overweight"
capdat$actbmi[capdat$BMXBMI >= 30] <- "Obese"

capdat$subsample[capdat$MEC == "examined" & 
                   capdat$sex == "female" &
                   capdat$agesamp == "subsample"] <- "subsample"
```

# More data management and selecting subsample

```{r}

#Getting the data for comparison analysis
finalset <- capdat %>%    
  filter(agesamp == "subsample")

finalset$ocp[finalset$ocp == 1] <- "Use"
finalset$ocp[finalset$ocp == 0] <- "Non-Use"

# Recode of BMI to expand groups
finalset$bmi[finalset$actbmi == "Overweight"] <- "Over/Obe"
finalset$bmi[finalset$actbmi == "Obese"] <- "Over/Obe"
finalset$bmi[finalset$actbmi == "Normal Weight"] <- "Norm/Und"
finalset$bmi[finalset$actbmi == "Underweight"] <- "Norm/Und"

# Model with collapsed perceived weight category
finalset$mesbmi[finalset$actbmi == "Overweight"] <- "Over/Obese"
finalset$mesbmi[finalset$actbmi == "Obese"] <- "Over/Obese"
finalset$mesbmi[finalset$actbmi == "Normal Weight"] <- "Normal"
finalset$mesbmi[finalset$actbmi == "Underweight"] <- "Under"

# Recode of predictor variable to collapse normal and underweight categories
finalset$perc[finalset$percbmi == "Underweight"] <- "Norm/Und"
finalset$perc[finalset$percbmi == "Normal Weight"] <- "Norm/Und"
finalset$perc[finalset$percbmi == "Overweight"] <- "Over"

finalsetRec <- finalset %>%
  mutate(percbmi = relevel(factor(percbmi), ref = "Normal Weight")) %>%
  mutate(eth = relevel(factor(eth), ref = "White")) %>%
  mutate(health = relevel(factor(health), ref = "Good/excellent"))%>%
  mutate(poverty = relevel(factor(poverty), ref = "Middle Income"))%>%
  mutate(bmi = relevel(factor(bmi), ref = "Norm/Und"))%>%
  mutate(insur = relevel(factor(insur), ref = "Insured"))%>%
  mutate(education = relevel(factor(education), 
                             ref = "Below High School"))%>%
  mutate(ocp = relevel(factor(ocp), ref = "Non-Use")) %>%
  mutate(perc = relevel(factor(perc), ref = "Norm/Und"))%>%
  #mutate(age10yr = relevel(factor(age10yr), ref = "20-29"))%>%
  mutate(mesbmi = relevel(factor(mesbmi), ref = "Normal"))%>%
  mutate(mismatch = if_else(bmiCalc == BMXBMI, "match", "not")) %>% 
  mutate(diffbmi = BMXBMI - bmiCalc) %>% 
  mutate(calcBMIcat = if_else(bmiCalc >= 18.5 & bmiCalc < 25, "Normal",
                              if_else(bmiCalc >= 25, "Overwt/obese",
                              "underweight"))) %>% 
  droplevels()

# get needed variables for analysis
finalsetRecSmall <- finalsetRec %>% 
  select(ocp, eth, bmi, insur, education, health, poverty, percbmi,mesbmi, calcBMIcat, perc, BMXBMI, RIDAGEYR) 

# get included/excluded to compare
finalsetRecSmall$insample <- complete.cases(finalsetRecSmall)

# examine included vs. computed BMI
cor(finalsetRec$bmiCalc, finalsetRec$BMXBMI, use = "complete.obs")
summary(finalsetRec$diffbmi)

```

# Compare included and excluded women in 20-49 age group

```{r}
# label the final variables for table format
label(finalsetRecSmall$RIDAGEYR)<-"Age (years)"
label(finalsetRecSmall$eth)<-"Race"
label(finalsetRecSmall$bmi)<-"Measured BMI (kg/m**2)"
label(finalsetRecSmall$mesbmi)<-"Measured BMI (kg/m**2)"
label(finalsetRecSmall$percbmi)<-"Peceived BMI"
label(finalsetRecSmall$insur)<-"Insurance"
label(finalsetRecSmall$poverty)<-"Poverty Income Ratio"
label(finalsetRecSmall$education)<-"Education Level"
label(finalsetRecSmall$health)<-"Perceived Health Status"
label(finalsetRecSmall$ocp)<-"Oral Contraceptive Use"
label(finalsetRecSmall$perc)<-"Perceived BMI small"

# make table comparing included and excluded
print(tableone::CreateTableOne(vars = c('RIDAGEYR','eth','education','health','poverty','percbmi','ocp', 'BMXBMI'), 
                             strata = 'insample', 
                             data = finalsetRecSmall),
      nonnormal = c('RIDAGEYR', 'BMXBMI'))

```

# Checking the association between OCP and measured BMI

```{r}
# get analytic data set
analyticData <- finalsetRecSmall %>% 
  filter(insample == 1)

# check BMI normality
analyticData %>% 
  ggplot(aes(x = BMXBMI)) +
  geom_histogram()
# not normal

# check BMI homogeneity of variances by OCP group
car::leveneTest(BMXBMI ~ ocp, data = analyticData)
# assumption passed

# check mann-whitney U for BMI by OCP use
wilcox.test(formula = analyticData$BMXBMI ~ analyticData$ocp,
            paired = FALSE)
# not statistically sig p = .06

```

# Table 1 perceived weight categories and covariates

```{r}
# check age normality
analyticData %>% 
  ggplot(aes(x = RIDAGEYR, fill = percbmi)) +
  geom_histogram() 
# not normal

# make table comparing included and excluded
print(tableone::CreateTableOne(vars = c('RIDAGEYR','ocp','eth','BMXBMI','education','health','poverty'),
                             strata = 'percbmi', 
                             data = analyticData),
      nonnormal = c('RIDAGEYR', 'BMXBMI'))

# show overall values for table
print(tableone::CreateTableOne(vars = c('RIDAGEYR','ocp','eth','BMXBMI','education','health','poverty'),
                             data = analyticData),
      nonnormal = c('RIDAGEYR', 'BMXBMI'))
```


# Regression models

```{r}
# Crude Model 
reg <- multinom(percbmi ~ BMXBMI, 
                data = analyticData)

t(exp(coef(reg))) 
exp(confint(reg))

```

```{r}
# Adjusted Model without OCP (Table 2)
adj <- multinom(percbmi ~ BMXBMI + eth + insur + health + poverty + education + RIDAGEYR, 
                data = analyticData)

t(exp(coef(adj))) 
exp(confint(adj))
```


```{r}
# Model with OCP (Table 3)
bmi3 <- multinom(percbmi ~ BMXBMI + eth + health + insur + poverty + education + RIDAGEYR + ocp, 
                data = analyticData)

t(exp(coef(bmi3))) # odds ratios
exp(confint(bmi3))
```

# Testing OCP moderation between BMI and Perceived Weight

```{r}
# Model 
plain3 <- multinom(percbmi ~ BMXBMI + eth + health + insur + poverty + education + RIDAGEYR + ocp,
                  data = analyticData)

################# INTERACTION MODELS #######################

# Model 
interaction3 <- multinom(percbmi ~ BMXBMI*ocp + eth + health + insur + poverty + education + RIDAGEYR, 
                        data = analyticData)

# Likelihood ratio test to test significance of interaction term 
lrtest(plain3, interaction3)

```

```{r}
# LR Test is significant meaning that oral contraceptive use is a significant moderator between BMI and perceived weight. New models will need to be made to stratify by ocp

# Stratified by ocp use (Table 4)
test1.4 <- multinom(percbmi ~ BMXBMI + eth + health + poverty + insur + education + RIDAGEYR, 
                 subset = ocp == "Use" , 
                 data = analyticData)
t(exp(coef(test1.4))) 
exp(confint(test1.4))

```

```{r}
# Stratified by overweight ocp non-use (Table 5)
test2.4 <- multinom(percbmi ~ BMXBMI + eth + health + poverty + insur + education + RIDAGEYR, 
                 subset = ocp == "Non-Use" , 
                 data = analyticData)

t(exp(coef(test2.4))) 
exp(confint(test2.4))

```

# Assumption checking

```{r}
# Testing the IIA assumption for the adjusted model and two stratified models 
finalDataForMlogit <- mlogit.data(data = analyticData,
                                  choice = "percbmi",
                                  shape = "wide")

# estimate the BMI adjusted model
mlogit.adjOcpMod <- mlogit(formula = percbmi ~ 0 | ocp + eth + health + poverty + insur + education + RIDAGEYR + BMXBMI,
                           data = finalDataForMlogit)
#summary(mlogit.adjOcpMod)

# estimate it with two outcome categories instead
mlogit.adjOcpModTwo <- mlogit(formula = percbmi ~ 0 | ocp + eth + health + poverty + insur + education + RIDAGEYR + BMXBMI,
                           data = finalDataForMlogit,
                           alt.subset = c("Normal Weight", "Underweight"))
#summary(mlogit.adjOcpModTwo)

hmftest(x = mlogit.adjOcpMod, z = mlogit.adjOcpModTwo)

# p-value is > .05 IIA assumption is met for the adjusted model

```

```{r}
# stratified models with ocp use  
finalsetRecNorm <- analyticData %>% filter(ocp == "Use")
finalDataForMlogitNorm <- mlogit.data(data = finalsetRecNorm,
                                  choice = "percbmi",
                                  shape = "wide")

mlogit.adjOcpModNorm <- mlogit(formula = percbmi ~ 0 | eth + health + poverty + insur + education + RIDAGEYR + BMXBMI,
                           data = finalDataForMlogitNorm)
#summary(mlogit.adjOcpModNorm)

# estimate it with two outcome categories instead
mlogit.adjOcpModNormTwo <- mlogit(formula = percbmi ~ 0 | eth + health + poverty + insur + education + RIDAGEYR + BMXBMI,
                           data = finalDataForMlogitNorm,
                           alt.subset = c("Underweight", "Normal Weight"))
#summary(mlogit.adjOcpModNormTwo)

hmftest(x = mlogit.adjOcpModNorm, z = mlogit.adjOcpModNormTwo)

# p-value is 1, assumption is met
```

```{r}


# stratified models ocp non-use
finalsetRecOvOb <- analyticData %>% filter(ocp == "Non-Use")
finalDataForMlogitOvOb <- mlogit.data(data = finalsetRecOvOb,
                                  choice = "percbmi",
                                  shape = "wide")

mlogit.adjOcpModOvOb <- mlogit(formula = percbmi ~ 0 | eth + health + poverty + insur + education + RIDAGEYR + BMXBMI,
                           data = finalDataForMlogitOvOb)

#summary(mlogit.adjOcpModOvOb)

# estimate it with two outcome categories instead
mlogit.adjOcpModOvObTwo <- mlogit(formula = percbmi ~ 0 | eth + health + poverty + insur + education + RIDAGEYR + BMXBMI,
                           data = finalDataForMlogitOvOb,
                           alt.subset = c("Underweight", "Normal Weight"))
#summary(mlogit.adjOcpModOvObTwo)

hmftest(x = mlogit.adjOcpModOvOb, z = mlogit.adjOcpModOvObTwo)
# p-value indicates assumption met
```















